name: Version Bump

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  version-bump:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for version bump
      id: version-check
      run: |
        # Run version manager script
        node scripts/version-manager.js > version-output.txt 2>&1
        echo "Script output:"
        cat version-output.txt
        
        # Check if version was updated
        if grep -q "Version updated:" version-output.txt; then
          echo "version_updated=true" >> $GITHUB_OUTPUT
          UPDATED_VERSION=$(grep "Version updated:" version-output.txt | grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+')
          echo "new_version=${UPDATED_VERSION}" >> $GITHUB_OUTPUT
        else
          echo "version_updated=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit version changes
      if: steps.version-check.outputs.version_updated == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add VERSION.json CHANGELOG.md
        git commit -m "chore: bump version to ${{ steps.version-check.outputs.new_version }}" || exit 0
        git push
        
    - name: Create release tag
      if: steps.version-check.outputs.version_updated == 'true'
      run: |
        git tag ${{ steps.version-check.outputs.new_version }}
        git push origin ${{ steps.version-check.outputs.new_version }}
        
    - name: Create GitHub Release
      if: steps.version-check.outputs.version_updated == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version-check.outputs.new_version }}
        release_name: Release ${{ steps.version-check.outputs.new_version }}
        body: |
          ## What's Changed
          
          See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for detailed changes.
          
          **Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ steps.version-check.outputs.previous_version }}...${{ steps.version-check.outputs.new_version }}
        draft: false
        prerelease: false